package eu.albina.model.enumerations;

public enum TerrainType {
	gullies_and_bowls,
	adjacent_to_ridgelines,
	distant_from_ridgelines,
	in_the_vicinity_of_peaks,
	pass_areas,
	shady_slopes,
	sunny_slopes,
	grassy_slopes,
	cut_slopes,
	wind_loaded_slopes,
	base_of_rock_walls,
	behind_abrupt_changes_in_the_terrain,
	transitions_into_gullies_and_bowls,
	areas_where_the_snow_cover_is_rather_shallow,
	transitions_from_a_shallow_to_a_deep_snowpack,
	highly_frequented_off_piste_terrain,
	little_used_backcountry_terrain,
	places_that_are_protected_from_the_wind,
	regions_exposed_to_the_foehn_wind,
	regions_with_a_lot_of_snow,
	regions_exposed_to_precipitation,
	regions_exposed_to_heavier_precipitation,
}
