image: maven:3-jdk-8

build:
  stage: build
  script: mvn --batch-mode install
  artifacts:
    paths:
      - target/albina.war

deploy to development:
  stage: deploy
  script: mvn --batch-mode --activate-profiles env-dev tomcat7:deploy
  environment:
    name: development
  only:
    - development
    - ci
