workflow:
  # https://docs.gitlab.com/ee/ci/yaml/#workflowrules
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH

image: maven:3-eclipse-temurin-21

variables:
    MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
    MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

cache:
    paths:
        - .m2/repository

production build:
    stage: build
    script:
        - apt-get update -y
        - apt-get install -y ghostscript imagemagick webp
        - if [ -e "../avalanche-warning-maps" ]; then rm -rf ../avalanche-warning-maps; fi
        - git clone --depth 1 https://gitlab.com/albina-euregio/avalanche-warning-maps.git ../avalanche-warning-maps/
        - mvn $MAVEN_CLI_OPTS --activate-profiles env-prod install
    artifacts:
        when: always
        paths:
            - target/albina.war
            - target/test-results/
        reports:
            junit:
                - target/surefire-reports/TEST-*.xml
                - target/failsafe-reports/TEST-*.xml
    rules:
        - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
        - if: $CI_COMMIT_TAG
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

deploy to development:
    stage: deploy
    script:
        - export TOMCAT_PATH=/albina_dev
        - export GIT_VERSION=$(git describe --tags)
        - mvn $MAVEN_CLI_OPTS --activate-profiles env-dev tomcat7:deploy -Dmaven.test.skip=true
    environment:
        name: development
    rules:
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
        - when: manual
          allow_failure: true

deploy to production:
    stage: deploy
    script:
        - export TOMCAT_PATH=/albina
        - export GIT_VERSION=$(git describe --tags)
        - mvn $MAVEN_CLI_OPTS --activate-profiles env-prod tomcat7:deploy -Dmaven.test.skip=true
    environment:
        name: production
    rules:
        - if: "$CI_COMMIT_TAG"
          when: manual
          allow_failure: true
