image: maven:3-jdk-8

build:
  script: "mvn install -B"
deploy to development:
  stage: deploy
  script: mvn --batch-mode --activate-profiles env-dev tomcat7:deploy
  environment:
    name: development
  only:
    - development
    - ci
