workflow:
  # https://docs.gitlab.com/ee/ci/yaml/#workflowrules
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH

image: maven:3-eclipse-temurin-21

variables:
    MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
    MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

cache:
    paths:
        - .m2/repository

production build:
    stage: build
    script:
        - apt-get update -y
        - apt-get install -y ghostscript imagemagick webp
        - if [ -e "../avalanche-warning-maps" ]; then rm -rf ../avalanche-warning-maps; fi
        - git clone --depth 1 https://gitlab.com/albina-euregio/avalanche-warning-maps.git ../avalanche-warning-maps/
        - export GIT_VERSION=$(git describe --tags)
        - mvn versions:set -DgenerateBackupPoms=false -DnewVersion=$GIT_VERSION
        - mvn $MAVEN_CLI_OPTS --activate-profiles env-prod install
        - mv target/albina*.jar target/albina.jar
    artifacts:
        when: always
        paths:
            - target/albina.jar
            - target/test-results/
        reports:
            junit:
                - target/surefire-reports/TEST-*.xml
                - target/failsafe-reports/TEST-*.xml
    rules:
        - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
        - if: $CI_COMMIT_TAG
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

deploy to development:
    stage: deploy
    before_script:
        - eval $(ssh-agent -s)
        - chmod 400 "$SSH_PRIVATE_KEY"
        - ssh-add "$SSH_PRIVATE_KEY"
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
        - cp "$SSH_KNOWN_HOSTS" ~/.ssh/known_hosts
        - chmod 644 ~/.ssh/known_hosts
    script:
        - export GIT_VERSION=$(git describe --tags)
        - mvn versions:set -DgenerateBackupPoms=false -DnewVersion=$GIT_VERSION
        - mvn $MAVEN_CLI_OPTS --activate-profiles env-dev package -Dmaven.test.skip=true
        - mv target/albina*.jar target/albina.jar
        - rsync -avz -e 'ssh -p2201' target/albina.jar $SSH_SERVER:/opt/albina-server-dev/albina.jar
        - ssh -p2201 $SSH_SERVER 'sudo /usr/bin/systemctl restart albina-server-dev.service'
    environment:
        name: development
    rules:
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
        - when: manual
          allow_failure: true

deploy to production:
    stage: deploy
    script:
        - export TOMCAT_PATH=/albina
        - export GIT_VERSION=$(git describe --tags)
        - mvn $MAVEN_CLI_OPTS --activate-profiles env-prod tomcat7:deploy -Dmaven.test.skip=true
    environment:
        name: production
    rules:
        - if: "$CI_COMMIT_TAG"
          when: manual
          allow_failure: true
