version: "3.9"
services:

  albina-db:
    image: mysql:latest
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_USER: ais
      MYSQL_PASSWORD: "MD>5:X*n%)1V"
      MYSQL_DATABASE: albina
    volumes:
      - ./src/main/resources/sql/albina_create.sql:/docker-entrypoint-initdb.d/albina_create.sql:Z
      - ./src/main/resources/sql/albina_init_docker.sql:/docker-entrypoint-initdb.d/albina_init_docker.sql:Z
      - mysql-data:/var/lib/mysql
    networks:
      - albina-network

  albina-server:
    build: .
    environment:
      ALBINA_DB_CONNECTION_URL: "jdbc:mysql://albina-db:3306/albina?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
      # ALBINA_JWT_SECRET: ""
    ports:
      - "8080:8080"
    networks:
      - albina-network
    depends_on:
      - albina-db

volumes:
  mysql-data:

networks:
  albina-network:
    driver: bridge
