version: "3.9"
services:

  albina-db:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_USER: ais
      MYSQL_PASSWORD: "MD>5:X*n%)1V"
      MYSQL_DATABASE: albina
    volumes:
      - mysql-data:/var/lib/mysql

  albina-server:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - albina-db

volumes:
  mysql-data:
