-- liquibase formatted sql
-- changeset albina:005_000050 failOnError:true

ALTER TABLE regions ADD ENABLE_OBSERVATIONS bit DEFAULT 0 NULL;
ALTER TABLE regions ADD ENABLE_MODELLING BIT DEFAULT 0 NULL;
UPDATE regions SET ENABLE_MODELLING=1,ENABLE_OBSERVATIONS=1 WHERE ID='AT-07';
UPDATE regions SET ENABLE_MODELLING=1,ENABLE_OBSERVATIONS=1 WHERE ID='ES-CT-L';
UPDATE regions SET ENABLE_MODELLING=1,ENABLE_OBSERVATIONS=1 WHERE ID='IT-32-BZ';
UPDATE regions SET ENABLE_MODELLING=1,ENABLE_OBSERVATIONS=1 WHERE ID='IT-32-TN';
