-- liquibase formatted sql
-- changeset albina:008_000200 failOnError:true

ALTER TABLE server_instances DROP COLUMN PUBLISH_AT_5PM;
ALTER TABLE server_instances DROP COLUMN PUBLISH_AT_8PM;
ALTER TABLE server_instances DROP COLUMN PDF_DIRECTORY;
ALTER TABLE server_instances DROP COLUMN HTML_DIRECTORY;
ALTER TABLE server_instances DROP COLUMN MAPS_PATH;
ALTER TABLE server_instances DROP COLUMN MEDIA_PATH;
ALTER TABLE server_instances DROP COLUMN MAP_PRODUCTION_URL;
ALTER TABLE server_instances DROP COLUMN SERVER_IMAGES_URL;
ALTER TABLE server_instances DROP COLUMN DANGER_LEVEL_ELEVATION_DEPENDENCY;
