rm /mnt/albina_files/latest/*
cp /mnt/albina_files/$1/ /mnt/albina_files/latest/
mv /mnt/albina_files/latest/$1_de.png /mnt/albina_files/latest/de.png
mv /mnt/albina_files/latest/$1_it.png /mnt/albina_files/latest/it.png
mv /mnt/albina_files/latest/$1_en.png /mnt/albina_files/latest/en.png
mv /mnt/albina_files/latest/$1_de.xml /mnt/albina_files/latest/de.xml
mv /mnt/albina_files/latest/$1_it.xml /mnt/albina_files/latest/it.xml
mv /mnt/albina_files/latest/$1_en.xml /mnt/albina_files/latest/en.xml
mv /mnt/albina_files/latest/$1_AT-07_de.xml /mnt/albina_files/latest/AT-07_de.xml
mv /mnt/albina_files/latest/$1_AT-07_it.xml /mnt/albina_files/latest/AT-07_it.xml
mv /mnt/albina_files/latest/$1_AT-07_en.xml /mnt/albina_files/latest/AT-07_en.xml
mv /mnt/albina_files/latest/$1_IT-32-BZ_de.xml /mnt/albina_files/latest/IT-32-BZ_de.xml
mv /mnt/albina_files/latest/$1_IT-32-BZ_it.xml /mnt/albina_files/latest/IT-32-BZ_it.xml
mv /mnt/albina_files/latest/$1_IT-32-BZ_en.xml /mnt/albina_files/latest/IT-32-BZ_en.xml
mv /mnt/albina_files/latest/$1_IT-32-TN_de.xml /mnt/albina_files/latest/IT-32-TN_de.xml
mv /mnt/albina_files/latest/$1_IT-32-TN_it.xml /mnt/albina_files/latest/IT-32-TN_it.xml
mv /mnt/albina_files/latest/$1_IT-32-TN_en.xml /mnt/albina_files/latest/IT-32-TN_en.xml
mv /mnt/albina_files/latest/$1_de_bw.xml /mnt/albina_files/latest/de_bw.xml
mv /mnt/albina_files/latest/$1_it_bw.xml /mnt/albina_files/latest/it_bw.xml
mv /mnt/albina_files/latest/$1_en_bw.xml /mnt/albina_files/latest/en_bw.xml
mv /mnt/albina_files/latest/$1_AT-07_de_bw.xml /mnt/albina_files/latest/AT-07_de_bw.xml
mv /mnt/albina_files/latest/$1_AT-07_it_bw.xml /mnt/albina_files/latest/AT-07_it_bw.xml
mv /mnt/albina_files/latest/$1_AT-07_en_bw.xml /mnt/albina_files/latest/AT-07_en_bw.xml
mv /mnt/albina_files/latest/$1_IT-32-BZ_de_bw.xml /mnt/albina_files/latest/IT-32-BZ_de_bw.xml
mv /mnt/albina_files/latest/$1_IT-32-BZ_it_bw.xml /mnt/albina_files/latest/IT-32-BZ_it_bw.xml
mv /mnt/albina_files/latest/$1_IT-32-BZ_en_bw.xml /mnt/albina_files/latest/IT-32-BZ_en_bw.xml
mv /mnt/albina_files/latest/$1_IT-32-TN_de_bw.xml /mnt/albina_files/latest/IT-32-TN_de_bw.xml
mv /mnt/albina_files/latest/$1_IT-32-TN_it_bw.xml /mnt/albina_files/latest/IT-32-TN_it_bw.xml
mv /mnt/albina_files/latest/$1_IT-32-TN_en_bw.xml /mnt/albina_files/latest/IT-32-TN_en_bw.xml
mv /mnt/albina_files/latest/$1_de.xml /mnt/albina_files/latest/de.xml
mv /mnt/albina_files/latest/$1_it.xml /mnt/albina_files/latest/it.xml
mv /mnt/albina_files/latest/$1_en.xml /mnt/albina_files/latest/en.xml
chmod 744 /mnt/albina_files/latest/*