ALTER TABLE `ais`.`avalanche_bulletin_daytime_descriptions`
ADD `AVALANCHE_SITUATION_3_ID` varchar(255) DEFAULT NULL,
ADD `AVALANCHE_SITUATION_4_ID` varchar(255) DEFAULT NULL,
ADD `AVALANCHE_SITUATION_5_ID` varchar(255) DEFAULT NULL