ALTER TABLE `ais`.`avalanche_problems`
ADD `DANGER_RATING` varchar(255) DEFAULT NULL,
ADD `AVALANCHE_SIZE` varchar(255) DEFAULT NULL,
ADD `SNOWPACK_STABILITY` varchar(255) DEFAULT NULL,
ADD `FREQUENCY` varchar(255) DEFAULT NULL