ALTER TABLE `ais`.`avalanche_situation`
ADD `ARTIFICIAL_DANGER_RATING` varchar(255) DEFAULT NULL,
ADD `ARTIFICIAL_AVALANCHE_SIZE` varchar(255) DEFAULT NULL,
ADD `ARTIFICIAL_AVALANCHE_RELEASE_PROBABILITY` varchar(255) DEFAULT NULL,
ADD `ARTIFICIAL_HAZARD_SITE_DISTRIBUTION` varchar(255) DEFAULT NULL,
ADD `NATURAL_DANGER_RATING` varchar(255) DEFAULT NULL,
ADD `NATURAL_AVALANCHE_RELEASE_PROBABILITY` varchar(255) DEFAULT NULL,
ADD `NATURAL_HAZARD_SITE_DISTRIBUTION` varchar(255) DEFAULT NULL,
ADD `TERRAIN_FEATURE_TEXTCAT` longtext DEFAULT NULL,
ADD `DANGER_RATING_DIRECTION` varchar(255) DEFAULT NULL