ALTER TABLE `ais`.`avalanche_bulletins`
ADD `AV_ACTIVITY_HIGHLIGHTS_NOTES` varchar(255) DEFAULT NULL,
ADD `AV_ACTIVITY_COMMENT_NOTES` varchar(255) DEFAULT NULL,
ADD `SNOWPACK_STRUCTURE_HIGHLIGHTS_NOTES` varchar(255) DEFAULT NULL,
ADD `SNOWPACK_STRUCTURE_COMMENT_NOTES` varchar(255) DEFAULT NULL,
ADD `TENDENCY_COMMENT_NOTES` varchar(255) DEFAULT NULL