ALTER TABLE `ais`.regions 
DROP COLUMN `CREATE_STATIC_WIDGET`;

ALTER TABLE `ais`.avalanche_reports 
DROP COLUMN `STATIC_WIDGET_CREATED`;

ALTER TABLE `ais`.regions 
DROP COLUMN `STATIC_WIDGET_SECONDARY_LOGO_COLOR_PATH`;