cp /mnt/albina_files_dev/$1/*.pdf /mnt/albina_files_dev/latest/
mv /mnt/albina_files_dev/latest/$1_AT-07_de.pdf /mnt/albina_files_dev/latest/AT-07_de.pdf
mv /mnt/albina_files_dev/latest/$1_AT-07_it.pdf /mnt/albina_files_dev/latest/AT-07_it.pdf
mv /mnt/albina_files_dev/latest/$1_AT-07_en.pdf /mnt/albina_files_dev/latest/AT-07_en.pdf
mv /mnt/albina_files_dev/latest/$1_IT-32-BZ_de.pdf /mnt/albina_files_dev/latest/IT-32-BZ_de.pdf
mv /mnt/albina_files_dev/latest/$1_IT-32-BZ_it.pdf /mnt/albina_files_dev/latest/IT-32-BZ_it.pdf
mv /mnt/albina_files_dev/latest/$1_IT-32-BZ_en.pdf /mnt/albina_files_dev/latest/IT-32-BZ_en.pdf
mv /mnt/albina_files_dev/latest/$1_IT-32-TN_de.pdf /mnt/albina_files_dev/latest/IT-32-TN_de.pdf
mv /mnt/albina_files_dev/latest/$1_IT-32-TN_it.pdf /mnt/albina_files_dev/latest/IT-32-TN_it.pdf
mv /mnt/albina_files_dev/latest/$1_IT-32-TN_en.pdf /mnt/albina_files_dev/latest/IT-32-TN_en.pdf
mv /mnt/albina_files_dev/latest/$1_de_bw.pdf /mnt/albina_files_dev/latest/de_bw.pdf
mv /mnt/albina_files_dev/latest/$1_it_bw.pdf /mnt/albina_files_dev/latest/it_bw.pdf
mv /mnt/albina_files_dev/latest/$1_en_bw.pdf /mnt/albina_files_dev/latest/en_bw.pdf
mv /mnt/albina_files_dev/latest/$1_AT-07_de_bw.pdf /mnt/albina_files_dev/latest/AT-07_de_bw.pdf
mv /mnt/albina_files_dev/latest/$1_AT-07_it_bw.pdf /mnt/albina_files_dev/latest/AT-07_it_bw.pdf
mv /mnt/albina_files_dev/latest/$1_AT-07_en_bw.pdf /mnt/albina_files_dev/latest/AT-07_en_bw.pdf
mv /mnt/albina_files_dev/latest/$1_IT-32-BZ_de_bw.pdf /mnt/albina_files_dev/latest/IT-32-BZ_de_bw.pdf
mv /mnt/albina_files_dev/latest/$1_IT-32-BZ_it_bw.pdf /mnt/albina_files_dev/latest/IT-32-BZ_it_bw.pdf
mv /mnt/albina_files_dev/latest/$1_IT-32-BZ_en_bw.pdf /mnt/albina_files_dev/latest/IT-32-BZ_en_bw.pdf
mv /mnt/albina_files_dev/latest/$1_IT-32-TN_de_bw.pdf /mnt/albina_files_dev/latest/IT-32-TN_de_bw.pdf
mv /mnt/albina_files_dev/latest/$1_IT-32-TN_it_bw.pdf /mnt/albina_files_dev/latest/IT-32-TN_it_bw.pdf
mv /mnt/albina_files_dev/latest/$1_IT-32-TN_en_bw.pdf /mnt/albina_files_dev/latest/IT-32-TN_en_bw.pdf
mv /mnt/albina_files_dev/latest/$1_de.pdf /mnt/albina_files_dev/latest/de.pdf
mv /mnt/albina_files_dev/latest/$1_it.pdf /mnt/albina_files_dev/latest/it.pdf
mv /mnt/albina_files_dev/latest/$1_en.pdf /mnt/albina_files_dev/latest/en.pdf
chmod 744 /mnt/albina_files_dev/latest/*