cp /mnt/albina_files_dev/$1/*.html /mnt/albina_files_dev/latest/
mv /mnt/albina_files_dev/latest/$1_AT-07_de.html /mnt/albina_files_dev/latest/AT-07_de.html
mv /mnt/albina_files_dev/latest/$1_AT-07_it.html /mnt/albina_files_dev/latest/AT-07_it.html
mv /mnt/albina_files_dev/latest/$1_AT-07_en.html /mnt/albina_files_dev/latest/AT-07_en.html
mv /mnt/albina_files_dev/latest/$1_IT-32-BZ_de.html /mnt/albina_files_dev/latest/IT-32-BZ_de.html
mv /mnt/albina_files_dev/latest/$1_IT-32-BZ_it.html /mnt/albina_files_dev/latest/IT-32-BZ_it.html
mv /mnt/albina_files_dev/latest/$1_IT-32-BZ_en.html /mnt/albina_files_dev/latest/IT-32-BZ_en.html
mv /mnt/albina_files_dev/latest/$1_IT-32-TN_de.html /mnt/albina_files_dev/latest/IT-32-TN_de.html
mv /mnt/albina_files_dev/latest/$1_IT-32-TN_it.html /mnt/albina_files_dev/latest/IT-32-TN_it.html
mv /mnt/albina_files_dev/latest/$1_IT-32-TN_en.html /mnt/albina_files_dev/latest/IT-32-TN_en.html
mv /mnt/albina_files_dev/latest/$1_de.html /mnt/albina_files_dev/latest/de.html
mv /mnt/albina_files_dev/latest/$1_it.html /mnt/albina_files_dev/latest/it.html
mv /mnt/albina_files_dev/latest/$1_en.html /mnt/albina_files_dev/latest/en.html
chmod 744 /mnt/albina_files_dev/latest/*