-- liquibase formatted sql
-- changeset legacy:000_000130 failOnError:true
-- comment create table avalanche_bulletin_daytime_descriptions
-- preconditions onFail:MARK_RAN
-- precondition-sql-check expectedResult:0 SELECT EXISTS( SELECT * FROM information_schema.TABLES WHERE TABLE_NAME = 'avalanche_bulletin_daytime_descriptions' AND TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = SCHEMA()) 
CREATE TABLE avalanche_bulletin_daytime_descriptions (
    ID varchar(191) NOT NULL,
    COMPLEXITY varchar(191),
    DANGER_RATING_ABOVE varchar(191),
    DANGER_RATING_BELOW varchar(191),
    ELEVATION integer,
    HAS_ELEVATION_DEPENDENCY bit DEFAULT FALSE,
    TERRAIN_FEATURE_ABOVE_TEXTCAT longtext,
    TERRAIN_FEATURE_BELOW_TEXTCAT longtext,
    TREELINE bit DEFAULT FALSE,
    AVALANCHE_PROBLEM_1_ID varchar(191),
    AVALANCHE_PROBLEM_2_ID varchar(191),
    AVALANCHE_PROBLEM_3_ID varchar(191),
    AVALANCHE_PROBLEM_4_ID varchar(191),
    AVALANCHE_PROBLEM_5_ID varchar(191),
    PRIMARY KEY (ID),
    CONSTRAINT FK_AVALANCHE_BULLETIN_DATIME_DESCRIPTION_AVALANCHE_PROBLEM_1 FOREIGN KEY (AVALANCHE_PROBLEM_1_ID) REFERENCES avalanche_problems (ID),
    CONSTRAINT FK_AVALANCHE_BULLETIN_DATIME_DESCRIPTION_AVALANCHE_PROBLEM_2 FOREIGN KEY (AVALANCHE_PROBLEM_2_ID) REFERENCES avalanche_problems (ID),
    CONSTRAINT FK_AVALANCHE_BULLETIN_DATIME_DESCRIPTION_AVALANCHE_PROBLEM_3 FOREIGN KEY (AVALANCHE_PROBLEM_3_ID) REFERENCES avalanche_problems (ID),
    CONSTRAINT FK_AVALANCHE_BULLETIN_DATIME_DESCRIPTION_AVALANCHE_PROBLEM_4 FOREIGN KEY (AVALANCHE_PROBLEM_4_ID) REFERENCES avalanche_problems (ID),
    CONSTRAINT FK_AVALANCHE_BULLETIN_DATIME_DESCRIPTION_AVALANCHE_PROBLEM_5 FOREIGN KEY (AVALANCHE_PROBLEM_5_ID) REFERENCES avalanche_problems (ID)
);

